version: '2'

services:
  telegram-bot:
    build: ./
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN:
      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_PAYMENT_TOKEN:
    networks:
      tstu_telegram_bot_network:
        ipv4_address: 172.36.0.2

networks:
  tstu_telegram_bot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/16
          gateway: 172.36.0.1
